config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get 'signup', to: 'users#new'
  get 'login' =>'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' =>'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :sessions, only: [:new,:create,:destroy]
  resources :microposts do
    member do
      post :favorite
      delete :unfavorite
    end
  end
  resources :relationships, only: [:create,:destroy]
  resources :microposts do
    member do
      get :retweet
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items =  current_user.feed_items.includes(:user).order(created_at: :desc).page params[:page]
      @following = current_user.following_users
      @follower = current_user.follower_users
      @favorite = current_user.favorite_microposts
    end
  end
end

app/views/static_pages/count.js.erb
$("#count").replaceWith("<%= escape_javascript(render('static_pages/count')) %>")

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
       
       <%= link_to "フォロー( " + @following.count.to_s + " )",followings_user_path(current_user) %><br>
       <%= link_to "フォロワー( " + @follower.count.to_s + " )",followers_user_path(current_user) %><br>
       <span id="count">
       <%= link_to "Favorite( <span id='fav_count'>".html_safe + @favorite.count.to_s + "</span> )".html_safe,favorites_user_path(current_user),data: {remote: true} %><br>
       </span>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
      
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= page_entries_info @feed_items %>
      <%= render 'shared/feed' %>
    
  <%= paginate @feed_items %>
   
  </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>