config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get 'signup', to: 'users#new'
  get 'login' =>'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' =>'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :sessions, only: [:new,:create,:destroy]
  resources :microposts do
    member do
      post :favorite
      delete :unfavorite
    end
  end
  resources :relationships, only: [:create,:destroy]
  resources :microposts do
    member do
      get :retweet
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
      before_save { self.email = email.downcase }
      validates :name, presence: true, length: { maximum: 50 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :favoritelist, class_name:  "Favorite",
                                     foreign_key: "favoriter_id",
                                     dependent:   :destroy
                                     
  has_many :favorite_microposts, through: :favoritelist, source: :favoritepost
  
  mount_uploader :avatar, AvatarUploader
    # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  #お気に入りに登録する
  def favorite(other_post)
    favoritelist.create(favoritepost_id: other_post.id )
  end
  
  def unfavorite(other_post)
    favoritelist.find_by(favoritepost_id: other_post.id).destroy
  end
  
  def favorite?(other_post)
    favorite_microposts.include?(other_post)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show,:edit,:update,:followings,:followers,:favorites]
  
  def show
      @microposts = @user.microposts.order(created_at: :desc).page params[:page]
      @following = @user.following_users
      @follower = @user.follower_users
  end
  
  def new
    @user = User.new
  end
  
  def edit
  end
  
  def update
   if @user.update(user_params)
      flash[:success] = "プロフィールを編集しました"
      redirect_to @user
    else
      render 'edit'
   end
  end
  
  def create
   @user = User.new(user_params)
   if @user.save
     flash[:success] = "Welcome to the Sample App!"
     redirect_to @user
   else
  	render 'new'
   end
  end
 
  def followings
     @following = @user.following_users
  end
  
  def followers
      @follower = @user.follower_users
  end
  
  def favorites
     @favorite = @user.favorite_microposts.order(created_at: :desc).page params[:page]
  end

private

  def user_params
	 params.require(:user).permit(:name,:email,:password,:password_confirmation,:description,:location,:avatar)
  end

  def set_user
   @user = User.find(params[:id]) 
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_favorite.html.erb
<span id="mypost_<%= mm.id %>"class="label label-warning">
     <%= link_to "Favorite", favorite_micropost_path(mm), data: {remote: true}, method: :post %>
</span>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_follow_list.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |g| %>
  <div><%= hidden_field_tag :followed_id, f.id %></div>
  <%= g.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_following.html.erb
<% following.each do |f| %>
<div class="panel panel-default">
    <div class="panel-body">
    <h2><%= gravatar_for f %>
 <div class="name">
     <%= f.name %>
     <div class="follow-btn"><%= render 'follow_form_for_list' ,f:f if logged_in? %></div></div></h2>
<div class="description"><%= f.description %></div>
<% if f.location.nil? %>
 <% else %>
<div class="panel-footer">Location:<%= f.location %></div>
<% end %>
</div></div>
<% end %>

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
  
   <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
   
  <%= image_tag @user.avatar.url if @user.avatar %>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  
   <%= f.label :name %>
   <%= f.text_field :name %>
   
   <%= f.label :email %>
   <%= f.text_field :email %>
 
   <%= f.label :password %>
   <%= f.password_field :password %>
   
   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation %>
   
   <%= f.label :description %>
   <%= f.text_area :description %>
   
   <%= f.label :location %>
   <%= f.text_field :location %>
   
   <% if params[:action] == 'new' or 'create' %>
    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% elsif params[:action] == 'edit' %>
    <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
    <% else %>
     <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
   <% end %>
  <% end %>

app/views/users/_unfavorite.html.erb
<span id="unfavorite_link_<%= mm.id %>" class="label label-default">
     <%= link_to "unFavorite", unfavorite_micropost_path(mm), data: {remote: true},  method: :delete %>
</span>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_unfollow_list.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id:f),
             html: { method: :delete },
             remote: true) do |g| %>
  <%= g.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
 </div>
</div> 

app/views/users/followers.html.erb
<h1>フォロワー(<%= @follower.count %>)</h1>
<br />
<div class="following">
<%= render partial:"following", locals:{following: @follower} %>
</div>

app/views/users/followings.html.erb
<h1>フォロー(<%= @following.count %>)</h1>
<br />
<div class="following">
<%= render partial:"following", locals:{following: @following} %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  
  
  <%= form_for(@user) do |f| %>
  
   <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

   <%= f.label :name %>
   <%= f.text_field :name %>
   
   <%= f.label :email %>
   <%= f.text_field :email %>
 
   <%= f.label :password %>
   <%= f.password_field :password %>
   
   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation %>

   <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  <% end%>
 </div>
</div> 

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <% if @user.avatar? %>
    <div class="thumbnail">
      <%= image_tag @user.avatar.url %>
    </div>
  <% end %>
        <%= gravatar_for @user %>
        <%= @user.name %></h1>
        <h2><%= link_to "フォロー( " + @following.count.to_s + " )",:controller => "users", :action => "followings" %><br>
        <%= link_to "フォロワー( " + @follower.count.to_s + " )",:controller => "users", :action => "followers" %>
        </h2>
      </section>
     <section class="user_description">
    <div class="panel panel-default">
    <div class="panel-heading">自己紹介</div>
   <div class="panel-body">
    <%= @user.description %>
   </div>
   </div>
  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
  <%= @user.location %>
    </section>
  </aside>
  <div class="col-md-8">
   <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= page_entries_info @microposts %>
        <%= render @microposts %>
      </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
</div>