config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get 'signup', to: 'users#new'
  get 'login' =>'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' =>'sessions#destroy'
  
  resources :users do
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :sessions, only: [:new,:create,:destroy]
  resources :microposts do
    member do
      post :favorite
      delete :unfavorite
    end
  end
  resources :relationships, only: [:create,:destroy]
  resources :microposts do
    member do
      get :retweet
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  paginates_per 5
  belongs_to :origin, class_name: "Micropost"
  
  has_many :favoriteuserlist, class_name:  "Favorite",
                                     foreign_key: "favoritepost_id",
                                     dependent:   :destroy
                                     
  has_many :favorite_user, through: :favoriteuserlist, source: :favoriter
  mount_uploader :image, ImageUploader
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 before_action :logged_in_user, only: [:create]

 def create
  @micropost = current_user.microposts.build(micropost_params)
  if @micropost.save
   flash[:success] = "Micropost created!"
   redirect_to root_url
  else
      @feed_items =  current_user.feed_items.includes(:user).order(created_at: :desc).page params[:page]
      @following = current_user.following_users
      @follower = current_user.follower_users
      @favorite = current_user.favorite_microposts
      render 'static_pages/home'
  end
 end

 def destroy
  @micropost = current_user.microposts.find_by(id: params[:id])
  return redirect_to root_url if @micropost.nil?
  @micropost.destroy
  flash[:success] = "Micropost deleted"
  redirect_to request.referrer || root_url
 end
 
 def retweet
  @origin = Micropost.find(params[:id]) 
  @micropost = current_user.microposts.build(content:@origin.content, origin:@origin)
  if @micropost.save
   flash[:success] = "Retweet created!"
   redirect_to root_url
  else
   render 'static_page/home'
  end
 end
 
     
  def favorite
    @micropost = Micropost.find(params[:id])
    current_user.favorite(@micropost)
    @favorite = current_user.favorite_microposts
   render 'microposts/favorite.js.erb'
  end

  def unfavorite
    @micropost = current_user.favorite_microposts.find(params[:id])
    current_user.unfavorite(@micropost)
    @favorite = current_user.favorite_microposts
    render 'microposts/unfavorite.js.erb'
  end
  
  
  
 private
  def micropost_params
	params.require(:micropost).permit(:content,:image,:image_cache)
  end
  
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
 <% if micropost.origin.blank? %>
 <%= link_to gravatar_for(micropost.user, size: 50),micropost.user %>
 <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
 <span class="content"><%= micropost.content %>
 <% if micropost.image? %>
 　　<span class="img"> 
    <%= image_tag micropost.image.url %>
    </span>
    <% end %></span>
 <span class="timestamp">
  Posted <%= time_ago_in_words(micropost.created_at) %> ago.
 </span>
  <% if current_user == micropost.user %>
   <span class="label label-danger">
     <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    </span>                              
   <% else %>
    <span class="label label-info">   
     <%= link_to "Retweet", retweet_micropost_path(micropost) %>
    </span>
   <% end %>
  <% else %>
   <%= link_to gravatar_for(micropost.origin.user, size: 50),micropost.origin.user %>
   <span class="user"><%= link_to micropost.origin.user.name, micropost.origin.user %></span>
   <span class="content"><%= micropost.content %>
   <% if micropost.origin.image? %>
 　　<span class="img"> 
    <%= image_tag micropost.origin.image.url %>
    </span>
    <% end %></span>
   <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
   </span>
    Retweeted from <%= micropost.origin.user.name %>.
   <span class="label label-danger">
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
   </span>
  <% end %>
  <% if current_user.favorite?(micropost) %>
   <%= render 'users/unfavorite', mm: micropost %>
  <% else %>
   <%= render 'users/favorite', mm: micropost %>
  <% end %>
 </li>

app/views/microposts/favorite.js.erb
$("#mypost_<%= @micropost.id %>").replaceWith("<%= escape_javascript(render('users/unfavorite', mm: @micropost)) %>")
$("#fav_count").html("<%= @favorite.count %>");

app/views/microposts/unfavorite.js.erb
$("#unfavorite_link_<%= @micropost.id %>").replaceWith("<%= escape_javascript(render('users/favorite', mm: @micropost)) %>");
$("#fav_count").html("<%= @favorite.count %>");